global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 10m
  receiver: 'slack-webhook'
  routes:
  - receiver: 'slack-webhook'
    matchers:
      - severity="critical"
    continue: true
receivers:
- name: 'slack-webhook'
  slack_configs:
  - send_resolved: true
  #  username: 'Alertmanager'
    channel: '#general'  
    api_url: 'https://hooks.slack.com/services/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'
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    title: |-
      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
      {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
        {{" "}}(
        {{- with .CommonLabels.Remove .GroupLabels.Names }}
          {{- range $index, $label := .SortedPairs -}}
            {{ if $index }}, {{ end }}
            {{- $label.Name }}="{{ $label.Value -}}"
          {{- end }}
        {{- end -}}
        )
      {{- end }}
    text: >-
      {{ range .Alerts -}}
      *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
      *Description:* {{ .Annotations.description }}
      *Details:*
        {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
        {{ end }}
      {{ end }}
