global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'metricsgateway'
    static_configs:
      - targets: ['pushgateway:9091']

# rule_files:
#   - 'alert-rules.yml'
# alerting:
#   alertmanagers:
#     - scheme: http
#     - static_configs:
#         - targets: ['alertmanager:9093']
