name: Docker Image Build

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and publish image
      uses: docker/build-push-action@v6
      with:
        context: "{defaultContext}:aws"
        file: docker/Dockerfile
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/simplyblockdeploy:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
