name: Docker Image Build

on:
  push:
    branches:
      - 'docker-build'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Tag docker image
      run: |
        docker build -t simplyblockdeploy .
        docker tag simplyblockdeploy:latest 565979732541.dkr.ecr.us-east-1.amazonaws.com/simplyblockdeploy:latest

    - name: Push the docker image
      run: |
        docker push 565979732541.dkr.ecr.us-east-1.amazonaws.com/simplyblockdeploy:latest
